### ISSUE TITLE
Reconnect loop

### ISSUE THREAD

**Issue by jonnew** [open-ephys-plugins/ephys-socket#11]
If a connection is lost, the plugin should attempt to reconnect by itself. The user should not have to manually disconnect and reconnect.

**Comment by jonnew** [comment]
More details on exactly what we want the behavior to be with no ideas on how to properly implement (except that we are moving into the territory where ZMQ might be useful instead of raw sockets). This is my understanding of what we were looking for since this is really used to get at the visualizer capabilities of the GUI and is not at all recommended for data saving:

1. The user starts streaming in Bonsai
2. The user connects in OE GUI and presses play
3. The user stops streaming in bonsai (presses stop button)
4. The user starts streaming again in bonsai (presses start button)
5. The OE GUI should now just start streaming the new data without the user having to press stop, disconnect, and reconnect. 

Because we are using TCP/IP you should be able to know when connection is lost and enter a reconnect loop. If the user presses stop in GUI, then the loop can be exited and the manual reconnect cycle required. @aa

@aacuevas may have additional ideas.

**Comment by aacuevas** [comment]
After further thinking about this, there is one issue that might be difficult to address is, that if Bonsai stops streaming, nothing ensures that when it starts again, configuration-time settings such as number of channels will remain the same. Or, even if the source is the same.

A reconnect loop should at least check if the settings are the same, and disconnect (and potentially stop GUI acquisition altogether) if there is a mismatch.

Going further, the main issue from user experience is that, if Bonsai stops, the GUI just source stops streaming and, to reconnect, a user has to: Stop the GUI, click disconnect, clock connect again, restart the GUI. Which is too much of a hassle. At the very least, steps should be taken to reduce this complexity.

A good starting point question is: When do we want, if at all, the plugin to stop acquisition? In the GUI, a hardware disconnection causes an immediate acquisition stop. Do we want a similar behavior? Do we want a try-reconnect loop and just stop if a mismatch? Do we want the loop and just not do anything if there is such mismatch?
