### ISSUE TITLE
Add the option to select a particular data type

### ISSUE THREAD

**Issue by jsiegle** [open-ephys-plugins/ephys-socket#2]
The plugin current assumes data is arriving as a `uint16_t` matrix. This should be configurable for other types of ints and floats.

**Comment by bparks13** [comment]
As of version 0.3.0, the incoming data packets must define the data type explicitly, based on OpenCV.Net.Mat Depth values. Data types are then correctly converted from whatever is specified in the header to a float for downstream manipulation in the GUI.
