### ISSUE TITLE
TCP server option

### ISSUE THREAD

**Issue by jonnew** [open-ephys-plugins/ephys-socket#6]
I created a `OpenCVMatTCPClient` (https://github.com/jonnew/Bonsai.JonsUtils/blob/master/Bonsai.JonsUtils/OpenCVMatTCPClient.cs) in the Bonsai Package. Should be pretty straightforward to implement a TCP server on the OE GUI side for guaranteed data delivery.

**Comment by bparks13** [comment]
Version 0.3.1 implements a TCP client on the GUI side, and the Bonsai code has been modified to serve as the TCP server (https://github.com/open-ephys/OpenEphys.Sockets.Bonsai).
